CREATE TABLE IF NOT EXISTS event_type (
     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
     name VARCHAR(60) NOT NULL UNIQUE,
     description TEXT,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);



